# Unique identifier for the project
sonar.projectKey=InvisID_Capstone
sonar.projectName=InvisID - Leak Attribution System
sonar.projectVersion=1.0

# Path to the source code
sonar.sources=app
sonar.exclusions=app/tests/**, app/storage/**, **/pycache/**, .venv/**

# Path to tests
sonar.tests=app/tests
sonar.test.inclusions=app/tests/**

# Language settings
sonar.python.version=3.12
sonar.language=python
sonar.python.bandit.reportPaths=app/bandit_report.json

# Encoding of the source code
sonar.sourceEncoding=UTF-8
